### ISSUE TITLE
Use of this package over python's stdlib DeprecationWarning?

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/zope.deprecation#18] opened 2023-03-26 14:41 UTC
At Plone, we are trying to re-architect the code base, which in plenty of times results in moving functionality provided by package A to package B.

To allow a smooth transition for consumers of package A, one can use either [Python's standard library warnings.warn](https://docs.python.org/3/library/warnings.html#warning-categories) or this `zope.deprecation` package.

I'm wondering if there is any advantage from one above the other... We have around ~100 hits for `zope.deprecation` and around ~60 hits for `DeprecationWarning`.

Given Zope history I can imagine that this package might even predate `warnings` stdlib module, but should it be time to retire it in favor of the upstream version, or are there some genuine features worth keeping? 🤔

TIA! 🙇🏾

**Comment by mmerickel** [comment] 2023-03-27 00:03
This library uses the stdlib warnings module. Every method exists to make it easier for user's to deprecate code by offering some simple helpers for various situations. For example it automatically adds proxy objects so that you can move the code without other custom workarounds.

The only feature I see that might be a duplicate of the stdlib is the ability to turn on/off warnings with the `deprecation.__show__` methods but folks can just ignore those.

**Comment by dataflake** [comment] 2023-03-27 04:55
I don't see why this package should be retired because one group of developers doesn't want to use it anymore. This makes no sense. `-1` from me.

**Comment by gforcada** [comment] 2023-03-27 08:27
Yes, indeed, as I asked to retire this one, sorry for the wording, my main motivation was to know, as @mmerickel mentions, if there is any advantage of keep using it or move to stdlib.

I guess that at Plone we do use these automatic proxy objects, so we can not do an almost automated migration from one to the other.

Thanks for the input 🙇🏾 

I will close it.

**Closed** 2023-03-28 06:26 UTC
